name: Issue Triggered
on:
  workflow_dispatch:
  issues:
    types: [ labeled ]
jobs:
  labeled:
    if: github.event.label.name == 'documentation'
    runs-on: ubuntu-latest
    steps:
    - name: "Print body for issue #${{ github.event.issue.number }}"
      run: echo "${{ github.event.issue.body }}"

    - name: "Body as JSON"
      shell: pwsh
      run: |
        $body = "${{ github.event.issue.body }}" -split [Environment]::NewLine | ConvertTo-Json -AsArray -Compress
        Write-Host $body
