name: Issue Triggered
on:
  workflow_dispatch:
  issues:
    types: [ labeled ]
jobs:
  labeled:
    if: github.event.label.name == "documentation"
    runs-on: ubuntu-latest
    steps:
    - name: Print body for issue #${{ github.event.issue.number }}
      run: echo "${{ github.event.issue.body }}"
